OP-TEE/manifest

hikey.xml
Point to OP-TEE build.git instead of personal repo
=> hikey: use official build.git

hikey.xml
Current version of strace is "master". This means it is
not a stable versionn, and may lead to compilation error
due to incompatible version of the components.
Latest stable version v4.10 is used instead
Change-Id: I0906606f4bfd67c4c4362bf428f30378066dad01
=> Hikey: use stable strace v4.10 version

default.xml, fvp.xml, hikey.xml, mt8173-evb.xml
busybox sha1 76915bf7 (2015-12-19) makes use of MTD_FILE_MODE_RAW.
This is correctly defined in linux/include/uapi/mtd/mtd-abi.h, but
unfortunately not in the toolchain headers
<toolchain>/arm-linux-gnueabihf/libc/usr/include/mtd/mtd-abi.h
Hence the previous sha1 is to be used, that is dbf5a6da
Change-Id: I6f96cd0cd23f0bcbfb18e719154e59d88d97379a
Tested-by: Pascal Brand <pascal.brand@linaro.org> (QEMU)
=> Latest busybox version cannot be used

default.xml
Full TrustZone support landed in upstream QEMU as of commit
3c2c85ec4b112e3e2b899472314d5da6880fdf0e
Suggested-by: Peter Maydell <peter.maydell@linaro.org>
Tested-by: Victor Chong <victor.chong@linaro.org>
=> default: Update repo to use upstream

hikey.xml
Update linux repo to point to v4.4 hikey-mainline-rebase branch
on https://github.com/96boards-hikey/linux
=> hikey: Update linux to point to mainline tracking

travis.xml
With this manifest, the "repo sync" phase on Travis takes less than one
minute vs. 4-6 minutes before.
travis.xml is created from default.xml and modified as follows:
- Add the clone-depth="1" attribute to all projects (shallow cloning)
- Change the BusyBox reference to the 1_24_0 tag. Previously, a SHA1
was used which would not work with shallow cloning.
Note that I could not get a similar result by simply using
"repo init --depth=1" (cloning would take longer).
=> Add travis.xml, similar to QEMU (default.xml) but cloning with depth 1

mt8173-evb.xml
As soon as, https://github.com/linaro-swg/linux/pull/3 has been merged, this manifest will be complete to setup and run everything with the new generic TEE driver on the MT8173-EVB device.
This manifest update contains more or less the same as in #20 , however, this points to the correct remote gits. I.e, #20 can be closed if and when this has been merged.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (MT8173-EVB)
=> mt8173: update for the generic driver

qemu_v8.xml
QEMU and OP-TEE on ARMv8 is working
Signed-off-by: Matt Ma <matt.ma@linaro.org>
=> qemu_v8: add first QEMU ARMv8 manifest

rpi3_experimental.xml
With the default clause setting a default revision, the hello world
repository fails to sync because there is only a master branch.
Override the default to point back to the master branch.
Change-Id: Id4d9a425a544f4470be04f80020f9fe25669c0f8
Signed-off-by: David Brown <david.brown@linaro.org>
=> Point RPi3's hello world to master

rpi3_experimental.xml
Prior to this commit, there was a few remotes pointing to non-Linaro
gits (optee_os, build etc), but since everything has been merged to the
official gits and branches we have update the manifest accordingly.
Change-Id: Ibd3c4782f22d31c576986a80f949318d2bbfb94d
=> rpi3: All remotes now pointing to official gits

travis.xml
QEMU master needs the following patch before we can use it again:
https://lists.gnu.org/archive/html/qemu-devel/2016-10/msg01979.html
Change-Id: Ic49fdfd83594b68d566990a411743f027dbd7778
=> travis.xml: checkout QEMU commit c5d128f because master is broken

travis.xml
Clone depth cannot be used when a revision is specified. It results in:
error: no such remote ref c5d128ffeb5357df1ea3e6de0c13b3d6a09f6064
Change-Id: I12b501ae2dbe40452814745085009285cc474c36
=> travis.xml: remove clone-depth="1"

mt8173-evb.xml
evb-utils contains scripts and binaries for updating the preloader,
which is necessary to be able to build and flash ARM-TF from scratch for
example.
The update procedure is as stated here:
1. cd <repo_root>/evb-utils
2. $ ./update-recover.sh
3. Hold the download key pressed, then press reset key
4. $ ./update.sh
5. Device should now just wait in fastboot ready to flash the rest of
the binaries.
=> mtk8173: Update repos used in mtk8173

mt8173-evb.xml
So, now I've tried syncing and building from this branch, i.e.,
```
repo init -u https://github.com/jbech-linaro/manifest.git -m mt8173-evb.xml -b mtk_xml_error
```
I got the source code and and it built, so now I hope there shouldn't be any mistakes. Apologize for the sloppiness.
=> mtk8173: Correct the line for evb-utils

qemu_v8.xml
Adds https://github.com/tianocore as edk2 repository
Change-Id: I5114063f6da98c03add52c7e9b81854ad7e02405
=> qemu_v8: add tianocore as edk2 repository

.travis.yml, default_stable.xml, dra7xx_stable.xml, fvp_stable.xml, hikey_debian_stable.xml, hikey_stable.xml, juno_stable.xml, mt8173-evb_stable.xml, qemu_v8_stable.xml, rpi3_stable.xml
So, I've tagged all the gits and I've updated all manifests (which this PR is about). I've added a second patch here on top that makes it possible to let Travis test manifest files. The changes in this PR seems to be OK, all builds [passed](https://travis-ci.org/jbech-linaro/manifest/jobs/219745438) after applying and using the 2.4.0 tag.
As you can see all "upstream" sections has been removed, this is something Pascal started removing on some projects and even though it's useful it's just a pain to maintain it. Instead people can use `$ git branch -a --contains <git>` instead if they want to know where the commit comes from.
=> Stable 2.4.0

hikey.xml, hikey_debian.xml
Change grub default branch from master to the last stable (2.02 tag)
Fixes: https://github.com/OP-TEE/build/issues/144
=> hikey: change grub default branch

.travis.yml
Force Travis to always use the branch from the originator, which means
that for both plain push and for pull requests it will use the
commiters own repository and commiters working branch.
I've tried this locally first and for that I created a local pull request also:
The PR passed: https://travis-ci.org/jbech-linaro/manifest/builds/238043712
The push itself passed: https://travis-ci.org/jbech-linaro/manifest/builds/238043694
And after merging ... it built the master, which also passed: https://travis-ci.org/jbech-linaro/manifest/builds/238219500
Hopefully this should solve our outstanding issues (and after this I plan to make the same change to build.git).
=> travis: Always use branch from the originator

qemu_v8.xml
Ubuntu 1.4.04 LTS, 16.04 LTS and even 17.04 provide the libfdt in
version 1.4.0. This version is too old for the latest QEMU that
requires libfdt in version 1.4.2 or higher.
This change updates qemu_v8.xml so that the qemu/dtc/ source code is
cloned locally and therefore the build does not depend on libfdt.
=> qemu_v8: clone DTC source

default.xml, default_stable.xml, qemu_v8.xml, qemu_v8_stable.xml
For the 2.5.0 release we found some regressions when running latest on
QEMU. After bisecting we managed to find where the issues where
introduced, they are as follows:
v8: (e75449a346) target/aarch64: optimize indirect branches
v7: (8a6b28c7b5) target/arm: optimize indirect branches
There is a fix for that upstream, but apparently that fix does not solve
the problems for TrustZone and therefore we need more time to
investigate it. Because of that we decided to temporarily use the
previous merge commit in QEMU that is working fine on both v7 and v8 and
that is:
(199e19e) Merge remote-tracking branch 'remotes/mjt/tags/trivial-patches-fetch' into staging
=> QEMU v7/v8: Use a known working revision

qemu_v8.xml
Do not use the EDK2 master branch because it is currently broken:
Building ... /home/jerome/work/optee_repo_qemu_v8/edk2/MdeModulePkg/Library/BootLogoLib/BootLogoLib.inf [AARCH64]
Segmentation fault (core dumped)
GNUmakefile:365: recipe for target '/home/jerome/work/optee_repo_qemu_v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/SerialDxe/SerialDxe/DEBUG/SerialDxe.efi' failed
make[2]: *** [/home/jerome/work/optee_repo_qemu_v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/SerialDxe/SerialDxe/DEBUG/SerialDxe.efi] Error 139
make[2]: Leaving directory '/home/jerome/work/optee_repo_qemu_v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/SerialDxe/SerialDxe'
Instead, use the last known good …
=> qemu_v8.xml: pin EDK2 version

hikey960.xml
With 92f365073cd8 ("lpm3, xloader: fix spi2 and i2c0 clock slow issue")
in tools-images-hikey960, the board won't boot. The kernel hangs at:
[0.753291] hi3660-mbox e896b000.mailbox: Mailbox enabled
[ 21.773459] INFO: rcu_preempt detected stalls on CPUs/tasks:
[ 21.779191] 5-...: (1 GPs behind) idle=135/140000000000000/0 softirq=21/22 fqs=2625
[ 21.787109] (detected by 0, t=5252 jiffies, g=-289, c=-290, q=111)
[ 21.793448] Task dump for CPU 5:
[ 21.796706] swapper/0 R running task 0 1 0 0x00000002
[ 21.803837] Call trace:
[ 21.806320] [] __switch_to+0x94/0xa8
[ 21.811513] [<0000000000000040>] 0x40
Work around this issue by pinning the parent commit in hikey960.xml.
Fixes: https://github.com/OP-TEE/optee_os/issues/1851
=> Pin tools-images-hikey960

hikey960.xml
This reverts commit 64873598f9f5d76769b01f333a8f882011750211.
Fixed in https://github.com/96boards-hikey/OpenPlatformPkg/pull/61.
=> Revert "Pin tools-images-hikey960"

fvp.xml
This is a first step in updating EDK2 on FVP. The new way of doing this will include grub. So we can merge this as a standalone patch and later patches would not need to be merged at the "same" time as this patch.
**EDIT** : Actually I need to push more patches to `manifest.git`, i.e., one for updating `ekd2`, so there will still be patches that are dependant on each other and would need to be merged at the same time. So, the comment above doesn't make that much sense due to that.
=> Add grub to the FVP manifest

qemu_v8.xml
The recent changes in [build.git](https://github.com/OP-TEE/build/commit/ab6226112e48979ab6a20dec09e978d34a793329) also affects QEMU v8. Therefore we need edk2-platforms in that setup also.
=> qemu v8: Use edk2-platforms

default_stable.xml, fvp_stable.xml, hikey_stable.xml, juno_stable.xml, mt8173-evb_stable.xml, qemu_v8_stable.xml
Due to linaro-swg/linux optee branch being overwritten to fix an error
in it's history, the existing commit cannot be checkout out anymore, so
replace it with the corresponding one in the branch that overwrote it.
=> Fix bad Linux kernel commit

rpi3_stable.xml
SHA-1 hashes can't be used mutually with clone-depth="1".
Although since Git version 2.5 servers may expose raw hashes,
it's common practice to disable this feature (it's
server-side configuration item) because of security flaws.
Fixes: https://github.com/OP-TEE/manifest/issues/88
=> rpi3: change firmware remote revision back to tag

hikey.xml, hikey960.xml, hikey_debian.xml, qemu_v8.xml
SourceForge is unreliable [1]. Use GitHub instead.
Change-Id: I73241adf4a0ce9b0a8985914ee4523f1d46e9207
Link: [1] https://travis-ci.org/OP-TEE/build/jobs/342160257#L621-L629
Suggested-by: Joakim Bech <joakim.bech@linaro.org>
=> Switch to GitHub for strace

default.xml
- Use GitHub as the (main) global remote.
- Use upstream busybox instead of tagged revision.
- Clone busybox from GitHub instead of busybox.net.
- QEMU still fails when trying upstream, hence keep the current tagged
revision.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU v7)
=> qemu tip: general cleanup and remote changes

travis.xml
Apply the same change as commit 07ac85cd90438 ("qemu: build using
buildroot") to the Travis manifest. This is needed because the Makefile
in build.git now expect buildroot. Fixes Travis error [1]:
make: *** buildroot: No such file or directory.  Stop.
Link: [1] https://travis-ci.org/OP-TEE/optee_os/builds/352735144#L2538
=> travis: build using buildroot

hikey.xml
After pinning all git's but OP-TEE and at the same time introducing the new l-loader (using recovery.bin) we introduced a flash regression for HiKey. This also affected [HAB](https://github.com/jbech-linaro/hikey_auto_boot/tree/webserver_python3) which forced me to turn HAB off temporarily. The fix was pretty easy though. It turned out that we needed to step up both Arm-TF and atf-fastboot to make be in sync with l-loader.
=> hikey: step up Arm-TF and atf-fastboot to match l-loader

make_stable.sh
This script will typically be used when we are about to release a new
OP-TEE version. The script will update all GitHub/OP-TEE gits likewise
it will also update all the gits we are hosting at GitHub/linaro-swg. It
will leave the "Misc" gits untouched.
If you want to see what it does, then simply just clone this git and run
```bash
$ ./make_stable.sh -o -r 3.1.0
```
Then run `git diff` and you will see the changes.
I know Jerome had a comment when I showed this at Connect about tagging in "linaro-swg" might interfere with existing tags (for example Linux kernel). It would be possible to tweak the script to prepend `optee_` for the gits in `github.com/linaro-swg` for example. In the end the tags there should never end up in the upstream project, it is just for our own sake, so I don't think …
=> Add helper script used for tagging releases

default.xml
Since commit bdc2df1e704d ("qemu: discard legacy bios mailbox and
support arm-tf boot scheme"), OP-TEE OS needs a new version of
bios_qemu_tz_arm.
Change-Id: I90c056416939e78b0b26f834eb174945be0e51ed
=> qemu: update bios_qemu_tz_arm

hikey960.xml
Commit f9f39124efd1 ("hikey*: support migration to BL2_EL3 on arm-tf")
in build.git has changed the name of nvme.img to hisi-nvme.img, to
reflect the latest name used in upstream tools-images-hikey960.git, after
commit b5ae2c13438e ("installer: add hisi- prefix to ptable, sec_xloader,
fastboot, sec_uce_boot, and sec_usb_xloader imgs").
Unfortunately the HiKey960 manifest still references an older version of
the project, which causes an error during "make flash":
$ make flash
[...]
fastboot flash nvme /home/jerome/work/optee_repo_hikey960/build/../tools-images-hikey960/hisi-nvme.img
error: cannot load '/home/jerome/work/optee_repo_hikey960/build/../tools-images-hikey960/hisi-nvme.img'
Makefile:322: recipe for target 'flash' failed
make: *** [flash] Error 1
Fix this by updating …
=> hikey960: update tools-images-hikey960

default.xml
Arm trusted firmware can boot op-tee qemu cortex-a15 for the qemu_virt setup.
This change bring arm-trusted-firmware source tree.
Required by https://github.com/OP-TEE/build/pull/252.
=> qemu: add arm trusted firmware

default.xml
make fails on Ubuntu 18.04 due to problems with glibc 2.27.
Some other projects had this problem with e2fsprogs:
https://forum.lede-project.org/t/any-device-build-fail-e2fsprogs-debugfs/12433
https://github.com/openwrt/openwrt/pull/781
and QEMU:
https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1753826
=> Bumped buildroot and qemu

rpi3.xml
Depends on https://github.com/OP-TEE/build/pull/268.
=> Rpi3: build using Buildroot

fvp.xml, hikey.xml, hikey960.xml, poplar.xml
To avoid build errors on Ubuntu 18.04 step up buildroot to the same
version used by the other platforms.
Change-Id: I3ff11e5de466a465774e75fafd34e5d54707a886
=> fvp, hikey, hikey960, poplar: step up buildroot

rpi3.xml
1. Switch to upstream ATF and U-boot
2. Use kernel v4.14 with OP-TEE applied patches.
Relates to https://github.com/OP-TEE/build/pull/269
https://github.com/OP-TEE/optee_os/pull/2394
=> rpi3: switch to upstream ATF, U-boot and kernel

default.xml, fvp.xml, hikey.xml, hikey960.xml, juno.xml, qemu_v8.xml
HiKey960 is now properly supported by upstream kernel v4.19, so drop the
platform-specific fork and use the new tip of our multi-platform
linaro-swg/linux/optee branch (which was recently rebased onto v4.19).
While we're at it, also upgrade other platforms.
Change-Id: I77d03d71350808561dfff0c90a4a8307ce274d9a
=> Update QEMU, QEMUv8, HiKey620, HiKey960, Juno and FVP to kernel v4.19

default.xml
There should be no need to clone qemu/dtc from the manifest file, QEMU
should handle that automatically. In fact I suspect this is the cause of
the following build error in Travis:
Cloning into '/home/travis/optee_repo/qemu/tests/fp/berkeley-softfloat-3'...
Cloning into '/home/travis/optee_repo/qemu/tests/fp/berkeley-testfloat-3'...
Cloning into '/home/travis/optee_repo/qemu/ui/keycodemapdb'...
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
Unable to fetch in submodule path 'dtc'
./scripts/git-submodule.sh: failed to update modules
Unable to automatically checkout GIT submodules ' ui/keycodemapdb tests/fp/berkeley-testfloat-3 tests/fp/berkeley-softfloat-3 dtc capstone'.
If you require use of an alternative …
=> default.xml: do not clone DTC

default.xml, dra7xx.xml, fvp.xml, hikey.xml, hikey960.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml
This updates TF-A to include the patch the fixes the boot regression on the old HiKey. Unfortunately there is not tag to use, so I've change all xml-files to use a defined commit now.
I've tested this on HiKey
```bash
repo init -u https://github.com/jbech-linaro/manifest.git -b tf-a-updates-emmc-fix -m hikey.xml --reference ~/devel/reference
```
and QEMU-v8
```bash
repo init -u https://github.com/jbech-linaro/manifest.git -b tf-a-updates-emmc-fix -m qemu_v8.xml --reference ~/devel/optee_projects/reference
```
The same repo commands can be used if you want to give it a try on another platform who are using TF-A.
Both boot up as expected and xtest passes.
```bash
23665 subtests of which 0 failed
90 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```
```bash …
```
=> Tf a updates emmc fix

README.md
All current documentation has been transferred to a new git called
optee_docs [1]. The output from optee_docs will be rendered using Sphinx
and hosted at optee.readthedocs.io [2]. The new documentation git will
also be part of the regular OP-TEE releases. For completeness, it will
also be included in our manifests making up a full OP-TEE developer
setup.
[1] https://github.com/OP-TEE/optee_docs
[2] https://optee.readthedocs.io
=> docs: Remove current docs and link to the new location

am43xx.xml, am57xx.xml, default.xml, dra7xx.xml, fvp.xml, hikey.xml, hikey960.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml
This relates to the changes in https://github.com/OP-TEE/build/pull/340. Here I've stepped up Linux kernel to the commit that we merged last week (5.1 based). I've also stepped up Buildroot to the commit just before optee_client was officially introduced in Buildroot. The reason for not using any later commit is because I saw some build regression with optee_client, when using build.git + more recent Buildroot. This means that if we want to step up Buildroot even more, then we must fix that issue.
When https://github.com/OP-TEE/build/pull/340 has been merged, I'll probably continue updating a few more builds (fvp, hikey and Rpi3), so they also track more or less the same commits as QEMU v7/v8.
=> Qemu v7/v8: Stepping up Linux kernel and Buildroot

default.xml
Add a link to GDB in build.git to make it easy and convenient to run gdb
from the same folder as used when compiling and running the full OP-TEE
developer setup.
=> qemu-v7: Link to the gdb binary on repo sync

hikey960.xml
Updates l-loader to the tip of branch testing/hikey960_v1.2. Fixes an
issue with "make recovery" remaining stuck at:
NOTICE:  BL1-FWU: *******FWU Process Started*******
"git bisect" reports that the fix is commit 461b27f4900b ("hikey960:
add Trusted Board Boot feature"). This commit allows for a bigger size
for TF-A BL1. The problem was introduced when we upgraded TF-A from
v1.5-rc2 to v2.0 [1] but was unnoticed at the time.
Fixes: [1] 5af25841ef84 ("Update Arm TF-A to v2.0")
Change-Id: I3ec8d782c1e12e4f9b03fbf6b03c41f3729ccb9d
=> hikey960: update l-loader

rpi3.xml
Add a new manifest for Raspberry Pi 3 B+ that pulls in
the start* firmware binaries needed to boot it up.
Signed-off-by: Philby John <philby.j@hcl.com>
Signed-off-by: Vv Ramya <ramyavv@hcl.com>
=> Add support for Raspberry Pi 3 B plus

am43xx.xml, am57xx.xml, dra7xx.xml
All OP-TEE related gits at GitHub will by default track the master
branch in the upstream gits, that is true also for optee_examples,
therefore let's remove the 'revision' from the optee_examples line in
the manifest files for TI devices.
=> TI: remove 'master' from revision in optee_examples

juno.xml
For some reason the juno.xml file was deleted in branch and tag 3.6.0.
Restore it.
Change-Id: I54f1e7134501ca9246236d069baa6ba8d21f79d3
=> Restore broken (empty) juno.xml

default.xml, fvp.xml, hikey.xml, hikey960.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml, synquacer.xml
Transition to the new trusted firmware repo location at
http://git.trustedfirmware.org.
=> Move trusted firmware repo to new location

README.md
The link in README.md was pointing to a non-existent location. It has been fixed to point to the proper section of the documentattion on building OP-TEE.
=> Fix link to "Manifests" section on ReadTheDocs.

poplar.xml
Switch to mainline U-boot remote and v2019.10 tag.
Signed-off-by: Igor Opaniuk <igor.opaniuk@gmail.com>
=> poplar: switch to v2019.10 mainline U-boot

default.xml, fvp.xml, hikey.xml, hikey960.xml, juno.xml, qemu_v8.xml
The optee branch in https://github.com/linaro-swg/linux has been
recently rebased onto Linux v5.5. Record this commit in the manifests.
Change-Id: I36da86d6d5f3d75057cc29b9f35310bd61d7a204
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMU)
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8)
Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey960)
=> Update QEMU, QEMUv8, HiKey620, HiKey960, Juno and FVP to kernel v5.5

default.xml, qemu_v8.xml, rpi3.xml
It seems like the newest version of repo (v2.0) no longer allows to
create symlinks to non-existent files. In the past repo has silently
ignored creating the symlink on the first repo sync. However the most
recent version gives an error instead.
Since our setup flow is to create toolchains after checking out the
repo forest, the only viable option we have is to no longer try to
create a symlink. This doesn't really affect anything as such, we just
had it there as a convenience so we could handle builds and debugging
from the same folder on disc.
=> repo: remove symlink creation to gdb

fvp.xml, hikey.xml, hikey960.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml, synquacer.xml
```
Updates all platforms except QEMU to TF-A to v2.2. This notably
includes support for using CNTPCT in TAs [2], and therefore fixes an
issue with function tracing:
$ make CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm32="-O0 -pg"
...
...
E/TC:? 0 User TA undef-abort at address 0x1921e8 ftrace_enter+284 .text+45512
E/LD:  Call stack:
E/LD:   0x001921e8 read_cntpct at optee_os/out/arm/include/generated/arm32_user_sysreg.h:33
E/LD:   0x00191f10 __gnu_mcount_nc at optee_os/lib/libutils/ext/arch/arm/mcount_a32.S:43
HiKey960: the OpenPlatformPkg repository is updated at the same time or
the board would hang on boot after the TF-A BL31 initialization message:
"NOTICE:  BL31: Built : <time and date>".
QEMU is not updated due to a regression in TF-A fixed in [2].
Link: [1] …
```
=> Update TF-A to v2.2

default.xml
Commit c91340cdbf11 ("Update TF-A to v2.2 (all platforms but QEMU)")
could not updated default.xml due to a regression upstream. The issue
has now been fixed, so we can reference a commit on the master branch.
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMU)
Change-Id: I975c174940256cce830c65fa5be370186bd1a931
=> qemu: Update TF-A to upstream master (v2.2-615-ge7a540335)

verdin.xml
This introduces OP-TEE-based setup for Verdin i.MX8M Mini [1].
Here mainline vanilla TF-A/OP-TEE/U-Boot and Linux are used.
Currently using my github forks for Linux/U-Boot/TF-A as not all patches
(mostly fixes + Verdin DT hierarchy for Linux kernel) are being
mainlined to correspondent projects.
[1] https://www.toradex.com/de/computer-on-modules/verdin-arm-family/nxp-imx-8m-mini-nano
Signed-off-by: Igor Opaniuk <igor.opaniuk@gmail.com>
=> verdin-imx8mm: add initial support

default.xml, fvp.xml, hikey.xml, hikey960.xml, juno.xml, qemu_v8.xml
Instead of using a fixed commit for Linux, track the tip of the "optee"
Linaro branch, like we do for other Linaro Gits (optee_*).
Change-Id: Iac3572e2d0567f7007fa1f6d4404dc51b3747352
=> Point to linaro-swg/linux.git branch optee

default.xml, qemu_v8.xml
Step up the QEMU version used by the OP-TEE builds for QEMU-v7 and -v8
to version 5.0.0. I've tested both of them and I've also tested running GDB (v7) and with `QEMU_VIRTFS_ENABLE=y` (v7). All seems to be working fine. The v8 writes this in the QEMU console
```
pflash_write: Write to buffer emulation is flawed
```
However, it doesn't seems to have any negative effects.
=> qemu-v7,v8: step up QEMU version to 5.0.0

default.xml, qemu_v8.xml
The 1st commit in the series (U-Boot version for Qemu/Armv7) depends on https://github.com/OP-TEE/build/pull/429.
=> Qemu Armv7/Armv8: upgrade boot packages

hikey.xml
Updates burn-boot to the latest version on the master branch, that is
commit a55c068f9a0a ("hisi-idt.py: port to Python 3"). Fixes errors when
flashing a board in recovery mode on a PC running Python 3 by default
(such as Ubuntu 20.04).
Change-Id: Icf7f44889021a223d958b92b730feea7e85dc187
=> hikey.xml: update burn-boot

make_stable.sh
Change script to use OP-TEE release tag for linaro-swg github Linux
kernel repository when applicable to make sure stable release are
referenced with a immutable reference of the kernel source tree.
This change assumes OP-TEE release tag is also created for that
repository.
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
=> make_stable: use OP-TEE tag for linaro-swg linux repository

default.xml, qemu_v8.xml
Step up the QEMU version used by the OP-TEE builds for QEMU-v7 and -v8
to version 5.1.0. Note that this version generates an internal Device
Tree with a /secure-chosen/kaslr-seed property [1]. Therefore OP-TEE
3.8.0 or later will run with Address Space Layout Randomization enabled
unless CFG_CORE_ASLR=n is set at build time.
Link: [1] https://git.qemu.org/?p=qemu.git;a=commit;h=60592cfed2b685ef114a454d176ef539528cb0cf
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv7)
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8)
Change-Id: If69490eaabd6437317111a0d1207c6715fc888ea
=> qemu-v7,v8: step up QEMU version to 5.1.0

make_stable.sh
When make_stable.sh replaces the linux project entry with a new one
pointing to a release tag, it lacks an XML closing tag '/>' which
causes an error with 'repo sync':
$ repo sync optee*
fatal: error parsing manifest /home/jerome/work/optee_repo_qemu/.repo/manifest.xml: not well-formed (invalid token): line 19, column 8
Add the missing bit.
Fixes: f7824ba5119e ("make_stable: use OP-TEE tag for linaro-swg linux repository")
Change-Id: Icfba9a60624804feadaf457ad9b54383f33f9aee
=> make_stable.sh: add missing closing tag

am43xx.xml, am57xx.xml, default.xml, dra7xx.xml, fvp.xml, hikey.xml, hikey960.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml, stm32mp1.xml, verdin.xml
Supports building with GCC 9.
Change-Id: Ieaa3a304ef3e414d0d067072d36e82a2eb2cc0e8
=> Update buildroot to 2020.08

default.xml, qemu_v8.xml
Consistent with the other OP-TEE/ and linaro-swg/ projects, use the
latest version of soc_term (the master branch) to avoid the need for a
manifest update when a bug is fixed in soc_term.
Change-Id: Iada78f11d7ce11afe5d3d9cf0a7916e0f2bfb299
=> qemu, qemuv8: use master branch for soc_term

hikey.xml
Having optee_benchmark available after repo init / repo sync is useful
from developer point of view as well from a testing point of view,
therefore add optee_benchmark to the hikey.xml manifest file.
=> hikey: add benchmark to the manifest

hikey.xml, hikey960.xml
Change the protocol used to clone Grub from Git to HTTPS. The latter is
more widely used and less likely to be unavailable or cause network
issues due to firewalls, etc. Today for instance the repository is
available over HTTPS but not over Git [1]:
fatal: read error: Connection reset by peer
error: Cannot fetch grub.git from git://git.savannah.gnu.org/grub.git
Link: [1] https://optee.mooo.com:5000/logs/OP-TEE/optee_test/469/529502990/fffbe60112bd663ce04c36016fc9cb516feb3d3c
Change-Id: I41de91edc455d3009baf683f9b4b24de1b5309c4
=> hikey, hikey960: use https: instead of git: to clone Grub

hikey.xml, hikey960.xml
When changing from git: to https:, the project path should have been
adjusted.
Fixes: d91661441a2d ("hikey, hikey960: use https: instead of git: to clone Grub")
Change-Id: Ib359bae00d047a2defd17210269a40433bef7011
=> hikey, hikey960: fix Grub URL

qemu_v8.xml
Updates EDK2 to tag edk2-stable201905, which brings Python3 support.
Project attribute sync-s="true" is added because this version of EDK2
has a couple of git submodules.
The most recent tags pull in a lot more code as submodules and that is
not really needed at the moment.
Change-Id: I96ffbf6736a28482fc1b3dfa8fd3b272ec1f5037
=> qemu_v8: udpate edk2 to tag edk2-stable201905

rpi3.xml
@jforissier , please wait with merging this until **after** we've released v3.12.0 (i.e., no hurry here). I took the liberty to just push the [rpi3-optee-5.4](https://github.com/linaro-swg/linux/tree/rpi3-optee-5.4) that I created earlier today (and cherry-picked the necessary patches) to our `linaro-swg/linux` tree. I can see that the RPi orgranisation have [more recent versions](https://github.com/raspberrypi/linux/branches). But the v5.4 seems to be what they promote right now, so I thought it's better to stop there first before jumping to v5.11 or something like that.
As an FYI I gave vanilla kernel from upstream a try also with [defconfig](https://github.com/torvalds/linux/blob/master/arch/arm64/configs/defconfig), but that didn't work.
=> rpi3: update the kernel version for RPi3B to v5.4

imx.xml
Adds support for i.MX 8MQuad Evaluation Kit (EVK), also know as
imx8mqevk.
Change-Id: I9eb761d49b0b7ae8701b984f8cb5b5ab54db1b3d
=> Add support for i.MX 8MQuad Evaluation Kit (EVK)

am43xx.xml, am57xx.xml, default.xml, dra7xx.xml, fvp.xml, hikey.xml, hikey960.xml, imx.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml, stm32mp1.xml, verdin.xml
As disscussed in https://github.com/OP-TEE/manifest/issues/179
+ Buildroot fixed the glibc 2.33 compatibility [issue](https://git.busybox.net/buildroot/commit/?id=f45925a951318e9e53bead80b363e004301adc6f) (`_STAT_VER` was removed in glibc 2.33), we should upgrade the Buildroot to reflect that change.
+ EDK2 fixed its incompatibility with python 3.9, so we should update it to edk2-stable202102
+ QEMU fails to build with binutils 2.35 (https://bugs.launchpad.net/ubuntu/+source/binutils/+bug/1907789), hence, we need to update it to the latest version.
=> Update Buildroot, EDK2 and QEMU

stm32mp1.xml
Bump u-boot to version v2021.04 and TF-A to version v2.4 in stm32mp1 platform manifest.
=> stm32mp1: bump u-boot to v2021.04 and tf-a to v2.4

default.xml, qemu_v8.xml
QEMU v6.0.0 was released on April 30, 2021. Update to this version.
=> qemu, qemu_v8: update QEMU to v6.0.0

qemu_v8.xml
For the unlucky people working behind a corporate proxy, it may be
difficult to access repositories using the git:// protocol. Use
https:// instead.
Change-Id: I80e53a03b86068d7cb2688d17c7ea6be59cab553
=> qemu_v8: use https:// instead of git:// for Xen repo

default.xml, qemu_v8.xml
Use latest Trusted Firmware-A release (v2.5).
Change-Id: If90f0a7148dc7873201e0025d55081f582849797
=> qemu, qemu_v8: use TF-A version v2.5

juno.xml
Removes the vexpress-firmware git as it's not needed any longer.
Change-Id: I9655bf23dd146fd642368bdff5cda574c6bfa5c1
Depends on https://github.com/OP-TEE/build/pull/500
=> juno: remove vexpress-firmware

hikey960.xml
Updagrade Trusted Firmware-A to version v2.5.
Change-Id: I211b78c5742facdecef1c5db8144cd2c8b2484cf
=> hikey960: upgrade trusted-firmware-a to v2.5

qemu_v8.xml
Xen 4.15.0 fixes a harmless but ugly warning:
$ make XEN_BOOT=y run
[...]
$ xtest 1013
[...]
o regression_1013.1.4 SHA-256 loop repeat 1000
(XEN) d0v0 Saved RPC cookie does not corresponds to OP-TEE's (ffff6439e9e00e00 != ffff6439e9e00a80)
(XEN) Xen WARN at optee.c:1147
(XEN) ----[ Xen-4.14.1  arm64  debug=n   Not tainted ]----
(XEN) CPU:    0
(XEN) PC:     000000000025c5ec optee.c#do_call_with_arg+0x4fc/0x510
(XEN) LR:     000000000025c5ec
(XEN) SP:     000080007ffdfd30
(XEN) CPSR:   80000249 MODE:64-bit EL2h (Hypervisor, handler)
(XEN)      X0: 00000000002f0028  X1: 0000000000000000  X2: 0000000000000000
[...]
regression_1013.1.4 OK
Link: https://github.com/OP-TEE/optee_os/issues/4715
Link: http://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=aace5466996e743a087153ad3f9d8fcf11a76c56 …
=> qemu_v8: update Xen to 4.15.0

qemu_v8.xml
```
This reverts commit 5e43cc04224de37452ac351451de48c4f8567772.
As mentioned in build.git commit f3ca6b20d9f0 ("qemu_v8.mk: Enable DomU
in Dom0 rootfs") [1]:
"
... it is essential to maintain the same version of Xen built in build
system and Xen tools built in Buildroot ...
"
Current Buildroot has Xen tools 4.14.2, so upgrading to Xen 4.15.0 is
not possible.
Fixes the following error:
buildroot login: root
cd /mnt/host/build/qemu_v8/xen
xl create guest.cfg
Parsing config from guest.cfg
libxl: error: libxl_create.c:671:libxl__domain_make: domain creation fail: Permission denied
libxl: error: libxl_create.c:1233:initiate_domain_create: cannot make domain: -3
Link: [1] https://github.com/OP-TEE/build/commit/f3ca6b20d9f0faf9a63bafbd57e1f668eace94de
Signed-off-by: Jerome Forissier …
```
=> Revert "qemu_v8: update Xen to 4.15.0"

hikey.xml
Updates the OpenPlatformPkg reporitory to the latest commit on branch
github/testing/hikey960_v1.3.4 (yes, it looks like this branch is for
HiKey960 but the previous commit was on this branch too).
Fixes an issue with "make flash" locking up at the first fastboot flash
command:
$ make flash
[...]
fastboot flash ptable /home/jerome/work/optee_repo_hikey/build/../l-loader/ptable-linux-8g.img
Sending 'ptable' (17 KB)
[Nothing happens here]
Change-Id: I72c63527a09363f7ad8fdaf772f30272c863900d
=> hikey: update OpenPlatformPkg

stm32mp1.xml
Dump to latest release tags TF-A v2.5 and U-Boot v2021.07.
Update U-Boot repository URL since it changed early 2021.
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Change-Id: Ifb555f9d233a9441db8c3dc644eb6da2faa35949
=> stm32mp1: bump to u-boot v2021.07 and tf-a v2.5

hikey.xml
Upgrade Trusted Firmware-A to version v2.5.
Change-Id: I19307a471cb7b6b240235b4de29069dfb382a452
=> hikey: upgrade trusted-firmware-a to v2.5

default.xml, qemu_v8.xml
Since build.git commit 1f9ad6d4a5fa ("qemu, qemu_v8: use soc_term.py")
[1], the soc_term project is not used anymore. Remove it from the QEMU
and QEMUv8 manifests.
Link: [1] https://github.com/OP-TEE/build/commit/1f9ad6d4a5fa
Change-Id: I1fdf9b369158d796d26107db957fb369b9e1e07d
=> qemu, qemu_v8: remove soc_term

qemu_v8.xml
Update the EDK2 version to edk2-stable202105 which includes the
following commit [1]: "UnitTestFrameworkPkg: Use TianoCore mirror of
cmocka repository". Fixes an issue with the original repository being
occasionally unreachable, which is inconvenient for end users and all
the more so for CI scripts [2].
Link: [1] https://github.com/tianocore/edk2/commit/2ad22420a710dc07e3b644f91a5b55c09c39ecf3
Link: [2] https://dev.azure.com/OPTEE/optee_os/_build/results?buildId=995&view=logs&j=705748f3-7146-5e86-79af-1c0266d20a8c&t=d3458a7d-1a81-5639-8e63-8927d807e53a&l=119
Change-Id: I11640a0ab3345817ba8aea10df31959157f6c3ee
=> qemu_v8: upgrade EDK2 to edk2-stable202105

qemu_v8.xml
TF-A version v2.5 requires the mbedtls version to be 2.26.0
to support trusted board boot. Older mbedtls version causes
compilation to break with TF_A_TRUSTED_BOARD_BOOT=y.
Fixes: 7b69f4 ("qemu, qemu_v8: use TF-A version v2.5")
Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>
=> qemu_v8: Fix the mbedtls version needed for TF-A v2.5

poplar.xml
Switch to 2021.07 U-Boot. Previous used U-Boot version (v2019.10) can
not be build with GCC10 (this is addressed already in commit 018921ee7
("Remove redundant YYLOC global declaration")).
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
=> poplar: switch to 2021.07 u-boot

am43xx.xml, am57xx.xml, default.xml, dra7xx.xml, fvp.xml, hikey.xml, hikey960.xml, imx.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml, stm32mp1.xml, verdin.xml, zynqmp.xml
Upgrading to the latest Buildroot release (2021.08).
Change-Id: I28f1fdebf4e68cb0833a352143c63a668c6a9250
=> Update buildroot to 2021.08

rpi3.xml
Upgrade TF-A to v2.5 and U-Boot to tag v2021.10
Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>
=> rpi3: Update TF-A and U-Boot

am43xx.xml, am57xx.xml, default.xml, dra7xx.xml, fvp.xml, hikey.xml, hikey960.xml, imx.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml, stm32mp1.xml, verdin.xml, zynqmp.xml
Update buildroot to version 2021.11. Fixes a build error with
qemu_v8.xml and "make XEN_BOOT=y check" (host compiler is
"gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0"):
../glib/gspawn.c: In function ‘safe_closefrom’:
../glib/gspawn.c:1497:7: error: too few arguments to function ‘close_range’
1497 |   if (close_range (lowfd, G_MAXUINT) != 0 && errno == ENOSYS)
|       ^~~~~~~~~~~
In file included from /usr/include/unistd.h:1204,
from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
from /usr/include/signal.h:328,
from /usr/include/x86_64-linux-gnu/sys/wait.h:36,
from ../glib/gspawn.c:25:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:56:12: note: declared here
56 | extern int close_range (unsigned int __fd, unsigned int __max_fd,
|            ^~~~~~~~~~~
Signed-off-by: Jerome Forissier …
=> Update buildroot to 2021.11

default.xml, fvp.xml, hikey.xml, hikey960.xml, imx.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml, stm32mp1.xml, synquacer.xml
Upgrade all platforms to the latest v2.x version of TF-A: QEMU, QEMUv8,
FVP, HiKey, HiKey960, Juno, RPi3 and STM32MP1.
Change-Id: I536be2a27d03569ad09467022ac80c11848e6feb
=> Upgrade trusted-firmare-a to v2.6

fvp.xml, qemu_v8.xml
MBed TLS has moved from https://github.com/ARMmbed/mbedtls to
https://github.com/Mbed-TLS/mbedtls [1], so update the URLs.
Link: [1] https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/ZFTDGEJHF2JUUT5KTFKY6B5JMGJNDZ2Q/
Change-Id: Ie2d1356528f7f64099e85a8b2e0e545b0a9d036a
=> fvp, qemu_v8: update MBed TLS URL

hikey.xml, hikey960.xml
Updates the l-loader commit to include commit "Convert
gen_loader_hikey.py and gen_loader_hikey960.py to Python 3". As a result
the whole project can be built without Python 2. The python3 command
MUST be available.
Change-Id: I519dd6b129c06eeed81a9af07101e9373515919b
=> hikey, hikey960: update l-loader for Python 3

qemu_v8.xml
With GCC 11.2.0 (default compiler on Ubuntu 22.04), EDK2 fails to build
with the following errors:
gcc  -c -I ./brotli/c/include -I .. -I ../Include/Common -I ../Include/ -I ../Include/IndustryStandard -I ../Common/ -I .. -I . -I ../Include/X64/ -MD -fshort-wchar -fno-strict-aliasing -fwrapv -fno-delete-null-pointer-checks -Wall -Werror -Wno-deprecated-declarations -Wno-stringop-truncation -Wno-restrict -Wno-unused-result -nostdlib -g -O2  brotli/c/dec/decode.c -o brotli/c/dec/decode.o
brotli/c/dec/decode.c:2033:41: error: argument 2 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} declared as a pointer [-Werror=vla-parameter]
2033 |     size_t encoded_size, const uint8_t* encoded_buffer, size_t* decoded_size,
|                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file …
=> qemu_v8: upgrade EDK2 to edk2-stable202202

qemu_v8.xml
Now that Xen is built from Buildroot, remove the top-level Xen repository.
Change-Id: Ie70e9d01d0b4b70fa58fa2bc002bb8a951f0f0d0
=> qemu_v8: remove Xen repo

default.xml, qemu_v8.xml
Upgrade QEMU to v7.0.0. This notably fixes build issues on some Linux
distributions [1].
Link: [1] https://github.com/OP-TEE/build/issues/568
Change-Id: Id24648ee11f885b354ebae2fae5dc0163f710987
=> qemu, qemu_v8: update QEMU to v7.0.0

rpi3.xml
The v5.17 branch here is based on the Raspberry Pi organizations 5.17.y
branch (and not from the official Linux kernel upstream tree).
Fixes: https://github.com/linaro-swg/linux/issues/102
=> rpi3: Update Linux to v5.17

fvp-ts.xml
Add new manifest file derived from the existing fvp.xml which includes
the Trusted Services project and its dependencies.
Related PR: https://github.com/OP-TEE/build/pull/571
=> fvp: add Trusted Services support

versal.xml
Initial manifest to build the Versal ACAP platform.
Tested on the Versal ACAP vck190.
While upstreaming progresses, two of the repositories reference Foundries.io so users can validate all the platform features (eFuse, TRNG, crypto, PUF etc)
It is the expectation that over the coming months - as merges take place - these two repositories will point to the AMD/Xilinx and OP-TEE projects instead.
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
=> versal: initial manifest

stm32mp1.xml
The boards stm32mp157c-dhcom-pdk [1] and stm32mp157a-dhcor-avenger96 [2] are supported since TF-A release v2.8.
[1] https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/commit/?id=eef485abb13b6df9a94137edd82904aab0ecf02d
[2] https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/commit/?id=51e223058fe70b311542178f1865514745fa7874
Signed-off-by: Johann Neuhauser <jneuhauser@dh-electronics.com>
Support of the boards stm32mp157c-dhcom-pdk and stm32mp157a-dhcor-avenger96  for the **OP-TEE developer setup** is completed after merging https://github.com/OP-TEE/manifest/pull/223 and https://github.com/OP-TEE/manifest/pull/219.
=> stm32mp1: bump TF-A to v2.8 to support new boards

stm32mp1.xml
The recent added board stm32mp157c-dhcom-pdk requires a dts fix [1] to not hang on boot
[1] https://source.denx.de/u-boot/u-boot/-/commit/48d9eaf6826a1816c5f9839a564ea6338da609a7
Signed-off-by: Johann Neuhauser <jneuhauser@dh-electronics.com>
Support of the boards stm32mp157c-dhcom-pdk and stm32mp157a-dhcor-avenger96  for the **OP-TEE developer setup** is completed after merging https://github.com/OP-TEE/manifest/pull/223 and https://github.com/OP-TEE/manifest/pull/219.
=> stm32mp1: bump U-Boot to 2022.10

stm32mp1.xml
Clone scp-firmware repository for integration of SCMI server reference implementation in OP-TEE when CFG_SCMI_SERVER=y.
The current scp-firmware mainline repository URL is [1] and is on process to move to [2]. However, implementation of OP-TEE environment support is scp-firmware is still under review in [3] hence here synchronize on Vincent's development branch until SCP-firmware officially support OP-TEE execution environment.
Change-Id: I7f86861cae4d017dc64b83a74fc243cde3ab2c0a
Link: [1] https://github.com/ARM-software/SCP-firmware.git
Link: [2] https://git.gitlab.arm.com/arm-reference-solutions/scp-firmware.git
Link: [3] https://github.com/vingu-linaro/SCP-firmware.git
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
=> [RFC] stm32mp1: add scp-firmware repository

qemu_v8.xml
Pin optee_rust to "Fix cargo error".
That fixed the Rust CI issue: https://github.com/OP-TEE/optee_os/pull/5705#issuecomment-1352816679
=> qemu_v8: Pin optee_rust to the latest version

fvp.xml
Also update Mbed-TLS to v2.28.1 to satisfy the requirements of the new TF-A version.
=> fvp: Update TF-A version to v2.8 for fvp-ts target

versal.xml
All xtests pass with 3.20
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
=> AMD/Xilinx Versal ACAP: update to upstream tree

am43xx.xml, am57xx.xml, default.xml, dra7xx.xml, fvp.xml, hikey.xml, hikey960.xml, imx.xml, juno.xml, poplar.xml, qemu_v8.xml, rockpi4.xml, rpi3.xml, stm32mp1.xml, verdin.xml, versal.xml, zynqmp.xml
Update Buildroot to the latest tag: 2022.11.1. This notably brings the opensc package (pkcs11-tool).
Change-Id: Ifaac6c2075ecc744e6127625b59f056061d1b404
=> Update Buildroot to 2022.11.1

make_stable.sh
Currently the script doesn't have filtering based on which type of element the line contains. This can lead to unexpected results or syntax errors, e.g. when using a "remove-project" element. Fix this issue by introducing an address to the sed expressions which narrows the scope down to only "project" type lines.
Resolves #226
=> Fix make_stable.sh

imx.xml
source.codeaurora.org is closed, use https://github.com/nxp-imx instead.
=> imx: use github instead of codeaurora

qemu_v8.xml
~~Please ignore the first commit ("qemu_v8: update U-Boot to v2023.07.02") which is submitted as https://github.com/OP-TEE/manifest/pull/243.~~ Edit: let's have both commits reviewed here.
=> QEMUv8: remove EDK2

fvp-ts.xml, fvp.xml
- Update the pinned version of TS and the TS TEE drivers. 
- For TS update change log see https://trusted-services.readthedocs.io/en/v1.0.0/project/change-log.html#version-1-0-0
- For TEE change log see https://gitlab.arm.com/linux-arm/linux-trusted-services/-/commit/a2d7349a96c3b3afb44bf1555d53f1c46e45a23d
- Update TF-A to v2.9.  This commit depends on https://github.com/OP-TEE/build/pull/693. The FVP will fail to boot without the SPMC manifest update.
=> Update Trusted Services to v1.0.0

stm32mp1.xml
Bumps U-Boot to release candidate tag v2024.01-rc1 to leverage STM32MP13 platforms updates.
=> stm32mp1: bump U-Boot to tag v2024.01-rc1

stm32mp1.xml
Syncs stm32mp1 manifest with SCP-firmware release tag v2.13.0 and sets its Git repository clone depth to a single commit.
=> stm32mp1: sync with scp-firmware release tag v2.13.0

qemu_v8.xml
Adds Xen repository to be used when compiling Xen, both the hypervisor itself and the user-space parts built with Buildroot.
=> qemu_v8: add Xen repository using tag RELEASE-4.18.0

qemu_v8.xml
Updates QEMU to v8.1.2.
This should fix the CI problem seen in https://github.com/OP-TEE/optee_os/pull/6534 with Hafnium.
=> qemu_v8: update QEMU to v8.1.2

qemu_v8.xml
SCP-firmware can be used to build a SCMI server as a PTA in optee-os. Add it to the manifest for qemu_v8.
=> qemu_v8: add SCP-firmware repository

qemu_v8.xml
Since major OP-TEE rust development will take place on no-std branch so use track that with qemu_v8 CI. This will give us confidence to make regular OP-TEE rust crates releases.
=> qemu_v8: rust: Switch to no-std branch

qemu_v8.xml
OP-TEE rust SDK build framework have been refactored to support 32-bit as well as 64-bit TAs build. Along with that mixed build options support is added where host applications build for 64-bit works with TAs build for 32-bit or vice-versa.
=> qemu_v8: rust: Uprev to no-std branch tip

poplar.xml
Switch to the latest U-Boot master which includes these fixes:
- 66a3618b9a poplar: provide more space for kernel image
- 01201dbd3b poplar: use random mac address
=> poplar: switch to latest u-boot master

rpi3.xml
Update Linux kernel to v6.7 for the RPi3B build. The branch is based on the forked kernel branch from the Raspberry Pi organization [1]. I've pushed the branch in question to https://github.com/linaro-swg/linux/tree/rpi3-optee-6.7. But for this particular PR, **we should hold of merging it until we've [released 4.1.0](https://github.com/OP-TEE/optee_os/pull/6574)**.
[1] https://github.com/raspberrypi/linux/tree/rpi-6.7.y
=> rpi3: Update Linux to rpi3-optee-6.7

common.xml
Don´t fetch optee_benchmark, as it's not used anymore.
=> common: remove optee_benchmark

common.xml
Update Buildroot to the latest released version. One nice side effect is that the source repository for the ncurses package has changed to a more reliable location (I have seen quite a few network timeouts and retries in CI recently, causing a job to exceed 4 hours of build time).
=> Update Buildroot to 2023.11.1

versal.xml
Due to legal requirements, we were obliged to relocate the TF-A repository from our private GitHub at Foundries.io. While the matter is settled I am redirecting TF-A to my personal repository.
=> versal: tf-a repository relocation

qemu_v8.xml
SCP-firmware has moved from github to Arm gitlab
=> qemu_v8: SCP-firmware repository relocation

fvp.xml
Remove the edk2 and grub components and use u-boot instead.
=> fvp: replace edk2+grub with u-boot

common.xml
The current Buildroot version (2023.11.1) causes a build error:
>>> libzlib 1.3 Downloading
wget --passive-ftp -nd -t 3 -O '/__w/optee_os/optee/out-br/build/.zlib-1.3.tar.xz.MFXZgl/output' 'https://www.zlib.net/zlib-1.3.tar.xz'
--2024-05-24 07:33:52--  https://www.zlib.net/zlib-1.3.tar.xz
Resolving www.zlib.net (www.zlib.net)... 85.187.148.2
Connecting to www.zlib.net (www.zlib.net)|85.187.148.2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
Update to the latest tag to make the error go away (will now get zlib-1.3.1.tar.xz).
=> Update Buildroot to 2024.02.2

common.xml
With more recent versions of GCC (v14.x), the build fails with implicit declaration of function open_temp_exec_file(...) in libffi. The issue is seen with GCC v14.1.1 and libffi v3.4.4. A fix for this issue was merged in libffi v3.4.6, which is the version we get when updating Buildroot to v2024.05.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (GCC 14.1.1/Fedora 40
and GCC 11.4.0/Ubuntu 22.04)
=> common: update buildroot to 2024.05

default.xml, poplar.xml
THe official domain name for U-Boot source code is source.denx.de not gitlab.denx.de. Update QEMU and Poplar accordingly. Other platforms are already using the correct URL.
Link: https://docs.u-boot.org/en/v2024.04/build/source.html [1]
=> qemu, poplar: get U-Boot from source.denx.de rather than gitlab.denx.de

stm32mp1.xml
Sync edk2-platform to fix build issue related to missing VariableFlashInfoLib resource as reported in build error trace message like the below:
edk2-platforms/Platform/StandaloneMm/PlatformStandaloneMmPkg/PlatformStandaloneMmRpmb.dsc(...): error 4000: Instance of library class [VariableFlashInfoLib] is not found
=> stm32mp1: update edk2-platform to fix VariableFlashInfoLib build issue

qemu_v8.xml, stm32mp1.xml
Sync scp-firmware for qemu_v8 and stm32mp1 with the changes applied by https://github.com/OP-TEE/optee_os/pull/6769.
=> qemu_v8 & stm32mp1: Sync SCP-firmware with its new integration in OP-TEE

fvp.xml
Let us add the hafnium component in order to enable building and testing SPMC at EL2. Also update TF-A to match Hafnium version at v2.10
=> fvp: Add hafnium component to enable running wih SPMC at EL2

fvp-ts.xml
Commit 20629b3153bc ("feat(sptool): generate `ARM_BL2_SP_LIST_DTS` file from `sp_layout.json`") introduces a bug in TF-A v2.10 which prevents generating FIP based SP packages. This was fixed in v2.11, thus updating TF-A version in fvp-ts.xml along its dependencies.
=> Update TF-A to v2.11 in fvp-ts.xml

fvp-ts.xml
The TSTEE driver used by Trusted Services has been merged to mainline Linux. Update the kernel version so we can use it and remove the old out-of-tree module. The linux-arm-ffa-user driver also needs to be updated for the new kernel.
=> fvp-ts: update to Linux v6.10

qemu_v8.xml
git.trustedfirmware.org has been unreliable and has caused CI errors a couple of times so switch to the GitHub mirrors instead. Another advantage is that GitHub is a bit faster.
Link: https://github.com/OP-TEE/optee_os/pull/6880#issuecomment-2160979548
Link: https://github.com/OP-TEE/optee_os/pull/6993#issuecomment-2290665315
=> qemu_v8: replace trustedfirmware.org repositories with their GitHub mirrors

qemu_v8.xml
https://github.com/ARM-software/arm-trusted-firmware is being deprecated in favor of https://github.com/TrustedFirmware-A/trusted-firmware-a, so use the new URL.
Suggested-by: Olivier Deprez <olivier.deprez@arm.com>
=> qemu_v8: update URL of TFA on GitHub

fvp.xml
TF-A pinned to v2.11 tag.
Hafnium pinned to v2.11+ commit hash permitting to build using clang 18
mbedTLS bumped to v3.6.0 recommended to be used along with TF-A v2.11.
Needed by https://github.com/OP-TEE/build/pull/781
=> FVP: bump TF-A/Hafnium v2.11

fvp-ts.xml
Update Trusted Services to the latest version on integration branch as of 2024-10-11.
The patch also removes the trusted-firmware-a and mbedtls entries from fvp-ts.xml because the included fvp.mk now has the same versions of these components.
=> fvp-ts: Update Trusted Services

qemu_v8.xml, stm32mp1.xml
SCP-firmware has released its new version v2.15.0 mid september. Move both qemu_v8 and stm32mp1 to use this official tag instead of the intermediate sha1. My 1st goal is to move qemu_v8 on this official version but I also made the change for stm32mp1 as they are following the same paths for SCMI server. This has been tested on qemu_v8 but not on stm32mp1. @etienne-lms could you test it ? Or should I remove stm32mp1 from this pull request ?
=> Move to SCP-firmware to the new v2.15.0 tag 

qemu_v8.xml
TF-A pinned to v2.11 tag. Hafnium pinned to v2.11+ commit hash permitting to build using clang 18.  mbedTLS bumped to v3.6.0 recommended to be used along with TF-A v2.11
Change-Id: If54f880ff6d61e47ecc2c6e955b63525a6c3546b
=> qemu_v8: update to TF-A/Hafnium v2.11

qemu_v8.xml
Upgrade Xen to RELEASE-4.19.0. This add support for FF-A notifications and avoids problems with kernels after v6.6.
=> qemu_v8: upgrade Xen to RELEASE-4.19.0

qemu_v8.xml
Upgrade QEMU to v9.2.0. This is needed to avoid error with the latest kernel like:
```
ERROR:../target/arm/internals.h:760:regime_is_user: code should not be reached Bail out!
ERROR:../target/arm/internals.h:760:regime_is_user: code should not be reached make: 
*** [Makefile:571: run-only] Aborted (core dumped)
```
Depends on https://github.com/OP-TEE/build/pull/798
=> qemu_v8: upgrade QEMU to v9.2.0

nanopc-t6.xml
Add support for the NanoPC-T6 [1]. Tested on a NanoPC-T6.
Link: [1] https://wiki.friendlyelec.com/wiki/index.php/NanoPC-T6
Signed-off-by: Ed Tubbs <ectubbs@gmail.com>
=> nanopc-t6: initial manifest

qemu_v8.xml
Add the Trusted Services git (v1.1.0) and the out-of-tree linux-arm-ffa-user (debugfs-v5.0.2) kernel driver for testing.
=> qemu_v8: add Trusted Services support

qemu_v8.xml
Add missing remote "tfo", from which `repo` will try to fetch newly added Trusted Services project. This resolves the following error that occurred when trying to `repo sync`.
```
fatal: remote tfo not defined in /home/optee/qemu-optee/.repo/manifest.xml
```
=> qemu_v8: add missing remote "tfo"

qemu_v8.xml
Update trusted-services.git to include the commit e9e0fedf8973 ("spm_test: allow configuring mem-region base addr.") to make the xtest -t spmc_ffa suite to pass on QEMU.
Need by https://github.com/OP-TEE/build/pull/802
=> qemu_v8: update Trusted Services

qemu_v8.xml
Upgrade SCP-firmware version to v2.16.0 which has been released mid march and includes the fix for the scp notification compilation among other things.
=> qemu_v8: upgrade scp firmware to v2.16.0

qemu_v8.xml
Update U-Boot to v2025.07-rc1.
This patch depends on: https://github.com/OP-TEE/build/pull/821
=> qemu_v8: Update U-Boot to v2025.07-rc1

qemu_v8.xml
Use https://github.com/xen-project/xen.git rather than https://xenbits.xen.org/git-http/xen.git for reliability reasons. From the OP-TEE OS CI logs:
repo has been initialized in /__w/optee_test/optee_repo_qemu_v8
error: Cannot fetch git-http/xen.git from https://xenbits.xen.org/git-http/xen.git
fatal: unable to access 'https://xenbits.xen.org/git-http/xen.git/': Failed to connect to xenbits.xen.org port 443 after 135097 ms: Could not connect to server
=> qemu_v8: clone Xen from its GitHub mirror

qemu_v8.xml
=> qemu_v8: Update TF-A to support Firmware Handoff

versal2.xml
Update the AMD TF-A, U-Boot, and Linux repository revisions to align with the AMD 2025.1 release version.
=> versal2: update revision to AMD 2025.1 release
