OP-TEE/manifest

README.md, mt8173_evb.xml
Signed-off-by: SY Chiu <sy.chiu@linaro.org>
Tested-by: SY Chiu <sy.chiu@linaro.org> (MT8173-EVB)
=> Added MediaTek MT8173 EVB

default_stable.xml, fvp_stable.xml, hikey_stable.xml, mt8173-evb_stable.xml
This release tag fixes
https://github.com/OP-TEE/optee_os/issues/494
=> Stable on Tag 1.0.1

hikey.xml
Move relevant repos from linaro-swg to 96boards.
=> hikey: Update repo sources

mt8173-evb.xml
Signed-off-by: James Kung <james.kung@linaro.org>
Tested-by: James Kung <james.kung@linaro.org> (MT8173-EVB)
=> MT8173 EVB support official kernel

fvp.xml
Change-Id: I57057b55f0cd8778618d46788823d41799ca7eef
=> fvp: use ARM-TF branch optee_paged_armtf_v1.2

default_stable.xml, fvp_stable.xml, hikey_stable.xml, mt8173-evb_stable.xml
Change-Id: I8b8db10aa8c38d3f0f8f9a75e2e9b747755a4e01
=> Update stable versions for 1.1.0

hikey.xml
=> hikey: patches_hikey should also use gendrv branch

juno.xml
Change-Id: I735cbe71c3f036b4ac6a1f2ec9c8d97c88557620
Depends on https://github.com/OP-TEE/build/pull/45
=> Add support for Juno

default.xml, fvp.xml, hikey.xml
=> Update qemu/fvp/hikey on the generic driver

juno.xml
Change-Id: I960467a504f89043675953ac5716fa63f9068b71
=> juno: update for the generic driver

default_stable.xml, hikey_stable.xml, juno_stable.xml, mt8173-evb_stable.xml
=> Release 2.0.0: stable versions

fvp_stable.xml
Change-Id: If43949b4a0b661c448641422f030fc59faed9bfe
=> fvp_stable: update optee_client path

travis.xml
Change-Id: Ib3c4d65d10667d3932bcac8ebab2baef2ee174af
=> Fix travis with respect to Generic Driver

hikey_debian.xml
This is dependent on:
* OP-TEE/optee_os/pull/744
* OP-TEE/build/pull/60
Change-Id: I026970e6dc9a52043d962b94019466d30d816152
=> hikey: Add debian xml-file (experimental)

hikey.xml, hikey_debian.xml
gendrv changes have been integrated into master branch
=> hikey: Use master branch for patches_hikey repo

hikey.xml, hikey_debian.xml
Change-Id: I709b7c07e66b520e69b7395b93baf4ef56231365
=> hikey: l-loader downloaded from https://github.com/96boards-hikey

default_stable.xml, fvp_stable.xml, hikey_debian_stable.xml, juno_stable.xml, mt8173-evb_stable.xml
Change-Id: I5c57cc2ce4671a16ff686d7a8cd23d69f2f0e228
=> Stable versions of manifests on 2.1.0

rpi3_experimental.xml
=> rpi3: Initial experimental setup for RPi3

default.xml, fvp.xml, hikey.xml, hikey_debian.xml, juno.xml, mt8173-evb.xml, qemu_v8.xml, rpi3_experimental.xml
=> Add hello_world repo

travis.xml
=> travis: Add Hello World repo

default_stable.xml, dra7xx_stable.xml, fvp_stable.xml, hikey.xml, hikey_debian.xml, hikey_debian_stable.xml, hikey_stable.xml, juno_stable.xml, mt8173-evb_stable.xml, qemu_v8_stable.xml, rpi3_stable.xml
Change-Id: Ifde84bf0e582c76b9a27a0ce64a71e07c30d966e
=> Stable versions of manifests on 2.3.0

am57xx.xml
=> am57xx: initial manifest

hikey_debian.xml
=> hikey_debian: Update repos for edk2, rpk v4.9 and stretch

default_stable.xml, dra7xx_stable.xml, fvp_stable.xml, hikey_debian_stable.xml, hikey_stable.xml, juno_stable.xml, mt8173-evb_stable.xml, qemu_v8_stable.xml, rpi3_stable.xml
Change-Id: I89b8960bd83167fcdf3608a83dbd8f077fcab637
=> Stable versions of manifests on 2.5.0-rc1

am43xx_stable.xml, am57xx_stable.xml, default_stable.xml, dra7xx_stable.xml, fvp_stable.xml, hikey_debian_stable.xml, hikey_stable.xml, juno_stable.xml, mt8173-evb_stable.xml, qemu_v8_stable.xml
Change-Id: I297b6e294f424cbef2c70cfc644d683c321d3065
=> Stable versions of manifests on 2.5.0

qemu_v8.xml, rpi3.xml
=> Add optee_benchmark repository for rpi3 and qemu_v8

.travis.yml
This should fix the build regression here:
https://travis-ci.org/OP-TEE/manifest/builds/257361594?utm_source=email&utm_medium=notification
=> Travis: add -p to mkdir

rpi3.xml
Fixes regression https://travis-ci.org/OP-TEE/build/jobs/257361518
`fatal: no revision for project optee_benchmark.git`
=> rpi3.xml regression: default remote branch

hikey.xml, hikey960.xml
Not to be used until build.git is updated.
=> hikey960: initial commit

am43xx.xml, am57xx.xml, default.xml, dra7xx.xml, hikey.xml, hikey960.xml, hikey_debian.xml, juno.xml, mt8173-evb.xml, qemu_v8.xml, rpi3.xml
Relates to:
https://github.com/linaro-swg/optee_examples/pull/1
https://github.com/OP-TEE/build/pull/170
=> examples: use optee_examples instead of hello_world

fvp.xml
Based on build results https://travis-ci.org/OP-TEE/build/builds/271755688
=> fvp: fix build, add optee_examples instead of hello_world rep

travis.xml
=> travis.xml: use optee_examples instead of hello_world

rpi3.xml
=> rpi3: add rpi3 firmware remote

rpi3.xml
=> rpi3: use rpi3 firmware stable branch

hikey.xml, hikey_debian.xml
=> hikey+debian: Adjust for upstream arm-tf

.travis.yml
=> travis: Enable hikey960

am43xx_stable.xml, am57xx_stable.xml, default_stable.xml, dra7xx_stable.xml, fvp_stable.xml, hikey960_stable.xml, hikey_debian_stable.xml, hikey_stable.xml, juno_stable.xml, mt8173-evb_stable.xml, qemu_v8_stable.xml, rpi3_stable.xml
I let Travis build this ([results](https://travis-ci.org/jbech-linaro/manifest/builds/334664408)). Besides timing out (hitting 50 minutes) on the RPi3 build it seems to work fine. I've done a local test with repo for QEMU v7 and that worked fine (clone, build + xtest).
// Joakim
=> OP-TEE 3.0.0 stable

default.xml
Change-Id: Ib9ba214170552ddbc041610c416de1648cf34cae
=> qemu: build using buildroot

fvp.xml
Change-Id: I0166d9931fbbf237ddad94d8342bb9edc7614f01
=> fvp.xml: build using buildroot

hikey.xml
Change-Id: I7572bf58524491a93104f10ab7ea7c5c10a72b9b
=> hikey.xml: build using buildroot

hikey960.xml
Change-Id: I65d6c20f4bd25464326ca8b4d330c9866b635015
=> hikey960.xml: build using buildroot

juno.xml
Change-Id: I1584f12526d18cc38e7ec1b3dbf60d40d52e6007
=> juno.xml: build using buildroot

poplar.xml
Test:
```bash
$ git repo init -u https://github.com/igoropaniuk/manifest.git -m poplar.xml -b poplar
$ repo sync -j20 && make all & make flash-help
```
=> poplar: initial manifest

default.xml
Change-Id: Ieb71eb16a947cbb85d2fc5c9e6f0930a9a45f0af
=> default.xml: replace bios_qemu_tz_arm with u-boot

default.xml, fvp.xml, hikey.xml, juno.xml, qemu_v8.xml
Change-Id: I96538461d9c45fb4d01dfd5251d143de1a1c551e
Tested-by: Jerome Forissier <jerome.forissier@Linaro.org> (QEMU, QEMUv8, FVP)
=> Update QEMU, QEMUv8, HiKey620, Juno and FVP to kernel v4.18

default.xml, fvp.xml, hikey.xml, hikey960.xml, juno.xml, poplar.xml, qemu_v8.xml, rpi3.xml
Change-Id: I3a55717d3dbcb415db655e266fe5a94c0eeea026
=> Update Arm TF-A to v2.0

hikey.xml
Updates l-loader and atf-fastboot for make recovery boot work again.
Change-Id: Idcd83c9066773fc0e041c0d230bceacfb6ba7872
=> hikey.xml: fix recover

rpi3.xml
```
+-----------------------------------------------------
23304 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
=> RPi3 updates

synquacer.xml
This provides initial manifest for DeveloperBox.
=> synquacer: add initial manifest

qemu_v8.xml
=> qemu_v8: add mbedtls repo

qemu_v8.xml, rpi3.xml, synquacer.xml
Small typos from the path update in  #144.
=> Fix TF-A for qemu_v8 and rpi3

poplar.xml
Switch to linaro-swg/linux repository.
Signed-off-by: Igor Opaniuk <igor.opaniuk@gmail.com>
=> poplar: switch to linaro-swg linux rep

fvp.xml
Signed-off-by: Javier Almansa Sobrino <javier.almansasobrino@arm.com>
=> Add support to build an fTPM service on FVP platform with Measured Boot

zynqmp.xml
Initial manifest document to build ZynqMP platform. In support to PR522
for build repository.
Signed-off-by: Ibai Erkiaga <ibai.erkiaga-elorza@xilinx.com>
=> zynqmp: initial manifest

qemu_v8.xml
Pin optee_rust to "Add expect script for OP-TEE CI"
Signed-off-by: Yuan Zhuang <zhuangyuan04@baidu.com>
=> qemu_v8: Pin optee_rust to the latest version

rockpi4.xml
Add support for the ROCK 4 board [1]. Tested on a 4B.
Link: [1] https://wiki.radxa.com/Rock4
Change-Id: I93d0cc9fef2df468448cb5fe79f41bf0f07a177a
=> rockpi4: initial manifest

qemu_v8.xml
Upgrade QEMU to v7.2.0.
Change-Id: I105c9b26fee99ef9fada953bc35b37965a24ff02
=> qemu_v8: Update QEMU to v7.2.0

fvp-ts.xml
Set fixed version for linux-arm-ffa-user, linux-arm-ffa-tee and trusted-services components in fvp-ts.xml.
=> fvp-ts: pin TS component versions

qemu_v8.xml
=> qemu_v8: upgrade TF-A to v2.10

fvp-ts.xml
Update Trusted Services to latest version.
Tested with 4.2.0-rc1.
=> fvp-ts: Update Trusted Services

default.xml
=> qemu: switch to v2024.07 u-boot

versal2.xml
Add initial platform support for AMD Versal Gen 2.
=> versal2: add initial platform support

versal_net.xml
Add support for the Versal Net variant of the AMD Versal.
=> versal_net: initial manifest

rockpi4.xml
Change-Id: I688949e84078fafc5485ca2b735ad6766740def1
=> rockpi4: Update U-Boot to v2025.01

LICENSE
Import LICENSE file from optee_os repository.
Closes: https://github.com/OP-TEE/build/issues/822
=> LICENSE: Add LICENSE file

default.xml
Depends on https://github.com/OP-TEE/build/pull/831
=> QEMU v7 Update QEMU and TF-A
